@echo off
echo Starting Sanjana Waterproofing Development Environment...
echo.
echo Starting Backend Server (MongoDB API)...
start "Backend Server" cmd /k "npm run server"
echo.
echo Waiting 3 seconds for backend to start...
timeout /t 3 /nobreak > nul
echo.
echo Starting Frontend Development Server...
start "Frontend Server" cmd /k "npm run dev"
echo.
echo Both servers are starting...
echo Backend: http://localhost:3001
echo Frontend: http://localhost:5174
echo.
echo Press any key to close this window...
pause > nul
